# Generated by Django 5.1.3 on 2026-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
