# Generated by Django 5.1.3 on 2026-01-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_base_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_rating',
        ),
    ]
