# Generated by Django 5.1.3 on 2026-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_store_produ_is_feat_a0ad0f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fallback_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
