# Generated by Django 5.1.3 on 2026-02-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
