# Generated by Django 5.1.3 on 2026-02-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_auth_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
