# Generated by Django 5.1.3 on 2026-02-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_delivery_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
