# Generated by Django 5.1.1 on 2026-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_alternate_mobile_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='email',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='identifier',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_delivery_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
