# Generated by Django 5.1.3 on 2026-02-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Journal', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='Full blog article'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(help_text='Short description for homepage cards', max_length=500),
        ),
    ]
