# Generated by Django 5.1.3 on 2026-02-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_blog_category_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='featured_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(max_length=500),
        ),
    ]
