# Generated by Django 5.1.1 on 2026-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancel_reason_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
